### ISSUE TITLE
Prevent Messages for web from breaking when the bridge is in use

### ISSUE THREAD

**Issue by outlandishphalanx** [mautrix/gmessages#8]
https://github.com/mautrix/gmessages/blob/97a3c97b8e75cc6e04d0893dfe2b39ce6aadb7be/libgm/gmproto/authentication.proto#L23

The field linked in the above proto is an enum field, with values 1 = WEB, 2 = TABLET, 3 = PWA.

If you pass 2 or 3 there then the pairing will be made as if it was from a tablet device or PWA. Because PWA & Tablet pairings are allowed to be active simultaneously with web pairings, it won't prevent the normal Messages for web client from working. Also, these pairing types would be a better fit for the bridge because they don't time out as quickly due to inactivity.

Pretending to be a tablet device would probably make the most sense because it's the most like a native mobile client. Each Messages phone client can be paired with up to two active tablet devices at the same time.

**Comment by tulir** [comment]
Interesting, that sounds great!

Do you happen to know if it also needs different user agents or a specific OS value? Sometimes when I link devices it gets logged out immediately, not sure if it's some kind of a ratelimit, wrong device details, or both

**Comment by outlandishphalanx** [comment]
AFAIK the user agent isn't actually used by the phone.

You can get signed out directly after making a pairing if you try to send a message to the phone too quickly, before the phone has received confirmation of the pairing from the backend and persisted it to its DB. So if the phone receives a message too quickly it will think it's coming from a device it doesn't recognize and unpair it. Unfortunately there's not a good way to know how long you need to wait, but adding a second or two of delay will greatly reduce the problem.

**Comment by tulir** [comment]
The OS field is used in the paired devices list on the phone (that's why I care about it: much nicer for the user if they see the bridge name instead of a random browser). It seemed like not using known values (like `Linux` or `Android`) made it get logged out more often, but I didn't test it very scientifically, so I guess it was just a coincidence. Adding a sleep between pair success and reconnect seems to have fixed it, thanks!

**Comment by tulir** [comment]
@outlandishphalanx Not related to this ticket, but since you seem to know everything about gmessages 😹: some users have reported issues with messages not getting sent (bridge sends request, but never gets a response from the phone, even though the phone is responding to other things), and with messages ending up in completely different chats (the participant id and/or conversation id seemingly being someone unrelated). Any hints for those? (if you do know/want to help, you can also join the #gmessages:maunium.net room on Matrix or DM me on any method listed on [mau.fi](https://mau.fi), probably nicer than GitHub)

**Comment by tulir** [comment]
Thanks, I haven't encountered the send issues on my own devices, but if some user who's technical enough to use `adb` hits it, I'll ask them to check those logs.

The wrong chat thing turned out to be an incorrect protobuf schema, incoming messages are actually `repeated`: https://github.com/mautrix/gmessages/commit/821849a25b910dee5a6175487514003328598e05. Apparently protobuf will silently squash data into one message instead of throwing an error when that happens, so both message parts (field #10, which was already `repeated`) were preserved, but the fact that it was actually two messages was lost.

**Comment by outlandishphalanx** [comment]
Oh, that's an interesting situation! Makes sense.
